import type { ForecastPriority } from "@/db/schema";

export type ForecastDTO = {
  id: string;
  productId: string;
  productName: string;
  productImageUrl: string | null;
  unit: string;
  currentStock: number;
  predictedDemand: number;
  suggestedOrderQty: number;
  confidenceScore: number;
  priority: ForecastPriority;
  reason: string;
  series: Array<{ date: string; actual?: number; predicted: number }>;
  willStockOutAt: string | null;
  generatedAt: string;
  /** "gemini" when generated by the real LLM forecast, "heuristic" when using the fallback. */
  engine?: "gemini" | "heuristic";
  predictedDemand30d?: number;
  marketDemandTrend?: "rising" | "stable" | "declining";
};

export type ForecastSummary = {
  totalItems: number;
  highPriority: number;
  mediumPriority: number;
  lowPriority: number;
  estimatedOrderAmount: number;
};
